- .ci/convert-test-data.sh
- .ci/gotestcover/LICENSE
- .ci/gotestcover/Makefile
- .ci/gotestcover/README.md
- .ci/gotestcover/gotestcover.go
- .ci/gotestcover/gotestcover_test.go
- .ci/lint.sh
- .ci/test-cover.sh
- .ci/test-integration.sh
- .ci/variables.sh
- .excludelint
- .gitignore
- .gitmodules
- .travis.yml
- Makefile
- README.md
cc @robskillington @martin-mao @cw9
> Set up travis and make targets

- aggregator/handler/logging.go
- services/m3aggregator/config/aggregator.go
- services/m3aggregator/config/config.go
- services/m3aggregator/main/main.go
cc @cw9 @jeromefroe @martin-mao 
This PR adds logging configuration to the top-level config so we can configure logging levels and log files etc.
> Add logging configuration

- aggregator/handler/forward.go
- aggregator/handler/forward_test.go
- server/msgpack/server_test.go
cc @jeromefroe @cw9 @martin-mao 
This PR fixes a few flaky forward handler tests due to parallel tests connecting to the same local test server.
> Fix flaky handler and server tests

- aggregator/aggregator.go
- aggregator/list.go
- aggregator/list_test.go
- aggregator/map.go
- glide.lock
- glide.yaml
cc @jeromefroe @cw9 @robskillington @martin-mao 
This PR reports various aggregator metrics.
> Report aggregator metrics

- aggregation/quantile/cm/options.go
- aggregation/quantile/cm/options_test.go
- aggregation/quantile/cm/stream.go
- aggregation/quantile/cm/stream_test.go
- aggregation/quantile/cm/types.go
- aggregation/timer.go
- aggregation/timer_test.go
- aggregator/elem.go
- aggregator/elem_test.go
- aggregator/options.go
- aggregator/options_test.go
- aggregator/types.go
- config/m3aggregator.yaml
- integration/data.go
- services/m3aggregator/config/aggregator.go
Which will be used in the custom aggregation change
@xichen2020 @jeromefroe
> Change stream to take in quantiles in ResetSetData

- aggregator/handler/forward.go
- aggregator/handler/forward_test.go
- services/m3aggregator/config/aggregator.go
cc @cw9 @prateek @jeromefroe @schallert @dgromov 
This PR adds metrics for the forward handler responsible for forwarding metrics from the agg tier to the downstream services.
> Add metrics for the forward handler

- aggregator/map.go
- aggregator/map_test.go
- integration/data.go
- integration/same_id_multi_type_test.go
cc @cw9 @jeromefroe @prateek 
This PR fixes an issue where metrics with the same ID but different types (e.g., a timer and a counter both with the name "foo") are mapped to the same entry, causing missing or incorrect aggregation results. Added unit tests and an integration test to catch the issue.
> Distinguish metrics with same id but different types

- .gitignore
- aggregator/aggregator_test.go
- aggregator/handler/blackhole.go
- aggregator/handler/broadcast.go
- aggregator/handler/broadcast_test.go
- aggregator/handler/config.go
- aggregator/handler/forward.go
- aggregator/handler/forward_options.go
- aggregator/handler/forward_test.go
- aggregator/handler/handler.go
- aggregator/list.go
- aggregator/list_test.go
- aggregator/options_test.go
- aggregator/ref_count_buffer.go
- aggregator/ref_count_buffer_test.go
- aggregator/types.go
- config/m3aggregator.yaml
- services/m3aggregator/config/aggregator.go
> Add a broadcast flush handler

- aggregation/timer_benchmark_test.go
- aggregation/timer_test.go
- aggregator/elem.go
- aggregator/elem_test.go
- aggregator/options_benchmark_test.go
- config/m3aggregator.yaml
- glide.lock
- glide.yaml
- services/m3aggregator/config/aggregator.go
> Fix config, make sure timer flush fast path is working

- .excludemetalint
- .metalinter.json
- .travis.yml
- Makefile
- aggregation/quantile/cm/sample.go
- aggregator/aggregator.go
- aggregator/aggregator_test.go
- aggregator/elem.go
- aggregator/elem_test.go
- aggregator/entry_test.go
- aggregator/flush_mgr.go
- aggregator/flush_mgr_options.go
- aggregator/list.go
- aggregator/mock/aggregator.go
- integration/client.go
- integration/custom_aggregation_test.go
- integration/data.go
- integration/election.go
- integration/integration.go
- integration/multi_client_one_type_test.go
- integration/one_client_multi_type_test.go
- integration/options.go
- integration/policy_change_test.go
- integration/same_id_multi_type_test.go
- integration/setup.go
- server/msgpack/options.go
- services/m3aggregator/config/aggregator.go
- services/m3aggregator/config/server.go
- services/m3aggregator/main/main.go
- tools/deploy/helper.go
This PR adds `gometalinter` to the `m3aggregator` repo and addresses any issues it finds.
cc @xichen2020 @prateek
> [gometalinter] Add gometalinter and address any issues it finds

- aggregator/aggregator.go
- aggregator/aggregator_test.go
- aggregator/flush_mgr_options.go
- aggregator/leader_flush_mgr.go
- aggregator/options.go
- aggregator/types.go
- glide.lock
- glide.yaml
- integration/setup.go
- services/m3aggregator/config/aggregator.go
- tools/deploy/helper.go
- tools/deploy/helper_options.go
- tools/deploy/helper_options_test.go
- tools/deploy/helper_test.go
> Up m3cluster version

- aggregator/aggregator.go
This PR adds a few metrics so we can observe placement changes more clearly.
> Add more metrics to observe placement changes

- aggregator/handler/writer/sharded.go
- aggregator/handler/writer/sharded_test.go
- aggregator/list.go
- server/msgpack/options.go
- server/msgpack/server.go
- services/m3aggregator/config/server.go
This PR removes some unnecessary verbose logging and sample error logs where necessary.
> Less verbose logging and sampling error logs

- aggregator/options.go
- aggregator/options_test.go
- aggregator/types.go
Updated the quantile function to generate ".p9999" rather than ".p99.99" for P9999
@xichen2020
> Update quantile suffix function

- aggregator/elem.go
- aggregator/elem_test.go
- aggregator/options_benchmark_test.go
- config/m3aggregator.yaml
- glide.lock
- glide.yaml
- integration/data.go
- services/m3aggregator/config/aggregator.go
> Pull in m3metrics with type string options

- aggregator/entry.go
- aggregator/entry_test.go
This PR fix an issue when ingesting metrics with tombstoned policies. Previously if the policies indicate the metric is tombstoned, the internal policies are updated and cached, and the entry is marked as tombstoned. This causes an issue when there are two different raw metrics matching the same rollup rule, one of which matches the rule and the other does not. As a result, the agg tier will receive a tombstoned policy for the second raw metric, mark the entry tombstoned, even though the entry is still very much alive due to the first raw metric still matching that rule and generating datapoints for that entry.
The fix is simply to not update the internal cached policies when receiving a tombstoned policy and instead rely on background ticking goroutine to sweep …
> Do not update cached policies when receiving tombstoned policies

- glide.lock
- glide.yaml
> Pull in logger change in kv

- aggregator/aggregator.go
This PR reports an error when a shard is not owned by the aggregator receiving the metric.
> Report shard not owned error

- server/msgpack/server.go
This PR always records the remote address in the error message since that's useful for debugging purposes in general.
> Record remote address on error

- tools/deploy/helper.go
- tools/deploy/helper_options.go
- tools/deploy/helper_options_test.go
- tools/deploy/helper_test.go
This PR explicitly passes in the placement to the deployment tool to simplify deployment logic and testing.
> Explicitly pass in placement for deployment

- .metalinter.json
- Makefile
> Add badtime linter

- glide.lock
- glide.yaml
cc @cw9 
This PR updates m3cluster dependency.
> Update m3cluster dependency

- aggregator/aggregator.go
- aggregator/aggregator_test.go
- glide.lock
- glide.yaml
This PR distinguishes different types of errors reported in the aggregator for better visibility and easier alerting configurations.
Fixes #83
> Distinguish different types of errors for better visibility

- glide.lock
- glide.yaml
This PR updates m3metrics to validate object type during decoding.
> Update m3metrics to validate object types during decoding

- .metalinter.json
- .travis.yml
- Makefile
This PR replays #104 onto master.
> Remove lint from build target (#104)

- aggregator/aggregator.go
- aggregator/list.go
- aggregator/list_test.go
- aggregator/map.go
- aggregator/map_test.go
- aggregator/tick_result.go
This PR replays #107 onto master.
> Distinguish tick metrics for standard metrics and forwarded metrics (#107)

- aggregator/election_mgr.go
- aggregator/flush_times_mgr.go
- aggregator/flush_times_mgr_test.go
- aggregator/follower_flush_mgr.go
- aggregator/follower_flush_mgr_test.go
- aggregator/list.go
- aggregator/list_test.go
- client/client.go
- client/client_test.go
This PR replays #108 onto master.
> Add logic to take into account forwarded metrics during deployment and leadership election (#108)

- client/client.go
- client/conn.go
- client/queue.go
- client/writer.go
- client/writer_mgr.go
- services/m3aggregator/config/aggregator.go
This PR adds a more comprehensive set of client-side metrics to allow us to gain more visibility.
> Add client metrics for better visibility

- client/client.go
- client/conn.go
- client/queue.go
- client/writer.go
- client/writer_mgr.go
- services/m3aggregator/config/aggregator.go
This PR replays #111 onto master.
> Add client metrics for better visibility (#111)

- aggregator/entry.go
- glide.lock
- glide.yaml
This PR pulls in the latest m3metrics.
> Pull in latest m3metrics

- aggregator/entry_test.go
- integration/data.go
> Fix integration test

- aggregator/aggregator.go
This PR records forwarding delay as histograms for forwarding metrics.
> Record forwarding delay as histograms

- aggregator/follower_flush_mgr.go
- aggregator/leader_flush_mgr.go
- aggregator/list.go
- client/queue.go
This PR adds more metrics for better visibility.
> Add more metrics for better visibility

- client/config.go
- client/config_test.go
- client/conn.go
- client/conn_options.go
- client/conn_options_test.go
- client/conn_test.go
This PR adds ability to optionally retry failed write attempts and the corresponding retry configuration.
> Add ability to retry failed write attempts

- glide.lock
- glide.yaml
> Update m3msg with encoder decoder interface change
