m3db/m3aggregator

- Makefile
Will re-use the targets in the `common.mk` from here - https://github.com/m3db/ci-scripts/pull/1
> reuse .ci/common.mk ci install targets

- aggregation/quantile/cm/options.go
- aggregation/quantile/cm/stream.go
- aggregation/quantile/cm/stream_test.go
- aggregation/quantile/cm/types.go
- aggregator/elem.go
- aggregator/elem_test.go
- aggregator/entry.go
- aggregator/entry_test.go
- aggregator/list_test.go
- aggregator/options.go
- config/m3aggregator.yaml
- glide.lock
- glide.yaml
- integration/data.go
- integration/setup.go
- server/msgpack/server.go
- server/msgpack/server_test.go
- services/m3aggregator/config/aggregator.go
- services/m3aggregator/config/config.go
- services/m3aggregator/config/server.go
- services/m3aggregator/handler/blackhole.go
- services/m3aggregator/handler/decode.go
- services/m3aggregator/handler/forward.go
- services/m3aggregator/handler/handler.go
- services/m3aggregator/handler/logging.go
- services/m3aggregator/main/main.go
cc @martin-mao @cw9 @prateek  @jeromefroe  
This PR adds config structs and example yaml so we can build the service binary out of the open source repo.
> Add config structs and config yaml to build service binary

- config/m3aggregator.yaml
- server/http/server.go
- services/m3aggregator/config/server.go
- services/m3aggregator/main/main.go
cc @cw9 @jeromefroe @martin-mao 
This PR uses the same port for the http server (which is used for debugging only) and the pprof endpoint. It also increase the HTTP server timeout in order to be able to successfully retrieve a 30s profile without getting EOF errors.
> Merge pprof and http ports

- aggregator/elem.go
- aggregator/elem_pool_test.go
- aggregator/elem_test.go
- aggregator/entry.go
- aggregator/entry_pool_test.go
- aggregator/entry_test.go
- aggregator/list_test.go
- aggregator/map_test.go
- aggregator/mock/aggregator.go
- config/m3aggregator.yaml
- glide.lock
- glide.yaml
- server/msgpack/server.go
- services/m3aggregator/config/server.go
cc @jeromefroe @cw9 @martin-mao 
This PR pulls in latest m3metrics PR (https://github.com/m3db/m3metrics/pull/35) and makes necessary changes to improve perf and memory utilization. The notable changes are:
* In normal cases when there are no policy changes, we reuse the same []byte in the unaggregated iterator for the metric id, therefore makes zero []byte allocation for ids. The only time when we need to create a new id is when there is a policy change, in which case we only make a copy if the id is not owned, and there are no existing reusable ids. 
* The policy slices are cached internally in the unaggregated iterator and are reused across metrics.
* The timer value []float64 slices are reused for non-large value slices (slices with no more than 1024 elements are considered non-large, …
> Pull in m3metrics improvements for better perf and memory utilization

- aggregator/aggregator.go
- aggregator/aggregator_test.go
- aggregator/entry.go
- aggregator/entry_test.go
- aggregator/list.go
- aggregator/map.go
- aggregator/map_test.go
- aggregator/mock/aggregator.go
- aggregator/options.go
- aggregator/result.go
- aggregator/shard.go
- aggregator/shard_test.go
- aggregator/types.go
- config/m3aggregator.yaml
- glide.lock
- glide.yaml
- integration/options.go
- integration/setup.go
- services/m3aggregator/config/aggregator.go
- services/m3aggregator/main/main.go
cc @robskillington @cw9 @jeromefroe @prateek 
Currently all the metrics are stored in a global map, which in turn also stores the element for each metric in a single list per resolution. While this works for small to medium qps, it doesn't scale as the number of unique metrics grows because we have SLAs on the list flush latency for each resolution, which worsens as there are more and more metrics put on the list.
This PR adds logic to shard metrics within each aggregation server so that each shard has its own map / list to store aggregated metrics. This reduce lock contention among metrics on the map, as well as the number of elements per list, which helps with the flush latency.
> Shard metrics within aggregation server

- aggregator/aggregator.go
- aggregator/aggregator_test.go
- aggregator/entry.go
- aggregator/entry_pool_test.go
- aggregator/entry_test.go
- aggregator/flush_mgr.go
- aggregator/flush_mgr_options.go
- aggregator/flush_mgr_test.go
- aggregator/list.go
- aggregator/list_test.go
- aggregator/map.go
- aggregator/options.go
- aggregator/shard.go
- aggregator/types.go
- config/m3aggregator.yaml
- integration/setup.go
- services/m3aggregator/config/aggregator.go
- services/m3aggregator/config/server.go
cc @robskillington @cw9 @jeromefroe @prateek 
This PR adds logic to coordinate flushes across aggregated metric lists in different shards in order to reduce spikiness in p99 flush latencies by controlling the concurrency of flushes and adding jitters to different flushes.
> Coordinate flushes across aggregated metric lists

- aggregation/quantile/cm/options.go
- aggregation/quantile/cm/options_test.go
- aggregation/quantile/cm/stream.go
- aggregation/quantile/cm/stream_test.go
- aggregation/quantile/cm/types.go
- aggregation/quantile/tdigest/tdigest.go
- aggregation/timer.go
- aggregation/timer_test.go
- aggregator/aggregator.go
- aggregator/list.go
- glide.lock
- glide.yaml
- server/msgpack/server.go
- services/m3aggregator/config/aggregator.go
cc @robskillington @cw9 @prateek @jeromefroe 
This PR contains various performance optimizations for the aggregation tier. Specifically, it includes
* Adding an option to provide a nil sample pool, which effectively disables sample pooling. The sample pool is used to provide sample objects for every timer value, which is on the critical path and is heavily contended. Profile shows getting values from the pool and putting values into the pool accounts for >30% of the CPU due to heavy contention. Disabling sample pooling significantly reduced write p99 (4ms -> 1ms) and flush p99 (1.5s -> 200ms).
* Adding an option to periodically flush streams at write time, therefore reducing processing load during global flushing. This has significantly improved flush p99 for aggregation servers that have …
> Various performance optimizations and bug fixes

- aggregation/counter.go
- aggregation/gauge.go
- aggregation/quantile/cm/options.go
- aggregation/quantile/cm/stream.go
- aggregation/quantile/cm/stream_test.go
- aggregation/quantile/cm/types.go
- aggregation/timer.go
- aggregator/elem.go
- aggregator/elem_test.go
- aggregator/entry.go
- aggregator/entry_test.go
- aggregator/list.go
- aggregator/options.go
- aggregator/types.go
- services/m3aggregator/config/aggregator.go
cc @cw9 @jeromefroe @prateek @dgromov 
This PR adds more performance optimizations for the agg tier, including:
* Make elem lock per time bucket. Previously we used to lock the entire element during writing or flushing, regardless of which time bucket we are writing too, resulting in higher lock contention than necessary. This PR now makes the lock per time bucket and thus more granular, so that writes to the current time bucket don't contend with reads from the previous time bucket during flushing.
* Add option to support periodic insertion and compression. For high frequency timers in large timer batches, it is very important to add timers as fast as possible. By only performing insertion and compression, I noticed a p99 write latency drop from 400ms to 30ms for higher frequency timer …
> More performance optimizations

- aggregator/handler/forward.go
- aggregator/handler/forward_options.go
- services/m3aggregator/config/aggregator.go
cc @cw9 @jeromefroe @prateek @dgromov 
This PR adds an option to provide write timeout for the forward handler so when one connection is blocked, the metrics will be retried on other connections.
> Add write timeout for forward handler

- aggregator/handler/config.go
So that adding a new handler under the broadcast handler won't affect current query.
@xichen2020
> Change metric name

- aggregation/counter.go
- aggregation/counter_test.go
- aggregation/gauge.go
- aggregation/gauge_test.go
- aggregation/options.go
- aggregation/options_test.go
- aggregation/timer.go
- aggregation/timer_test.go
- aggregator/elem.go
- aggregator/elem_test.go
- aggregator/entry_test.go
- aggregator/options.go
- aggregator/options_benchmark_test.go
- aggregator/options_test.go
- aggregator/types.go
- config/m3aggregator.yaml
- glide.lock
- glide.yaml
- integration/custom_aggregation_test.go
- integration/data.go
- services/m3aggregator/config/aggregator.go
Reordered functions in aggregator.Options.
Allow suffix override through config per metrics type per aggregation type.
@xichen2020
> Add default aggregation types for Counter and Gauge

- glide.lock
- glide.yaml
cc @cw9 
This PR pulls in latest m3metrics to enable TCP keepalives for the agg server.
> Pull in latest m3metrics to enable tcp keepalives

- config/m3aggregator.yaml
- glide.lock
- glide.yaml
- server/msgpack/options.go
- server/msgpack/server.go
- server/msgpack/server_test.go
- services/m3aggregator/config/server.go
- services/m3aggregator/main/main.go
cc @cw9 @prateek @jeromefroe 
This PR adds keepAlive options for the aggregation server to actively close out connections that have been closed by the client.
Fixes #34 .
> Provide keepAlive options for the aggregation server

- services/m3aggregator/config/aggregator.go
- services/m3aggregator/config/aggregator_test.go
This PR fixes a bug that computes max jitter based on different flush intervals and added some unit tests.
> Compute max jitter properly

- aggregator/election_mgr.go
- aggregator/election_mgr_options.go
- aggregator/election_mgr_test.go
- services/m3aggregator/config/aggregator.go
cc @jeromefroe @cw9  @martin-mao 
This PR removes the verify timeout and make the goroutine that verifies pending follower state only responsible for setting follower state. 
Previously when the verification times out, the goroutine may set the election state to the leader state if the current instance is the leader, however there was a race condition where if the leader changes right after timing out, the election state was incorrectly set to leader. This PR fixed the issue by only allowing the verification goroutine to set election state to follower state iff the state has not changed since verification starts. Also added unit tests.
> Verify pending follower only sets follower state

- .metalinter.json
- integration/client.go
- integration/data.go
- integration/election.go
- integration/integration.go
- integration/options.go
- integration/setup.go
@prateek reminded me in a different PR that we need to include build tags to some of the `gometalinter` subcommands so they lint the `integration` package properly. This diff adds those build flags and updates the package accordingly to remove the `nolint` flags which are now unnecessary.
cc @xichen2020 @prateek
> [gometalinter] Add build tags to gometalinter subcommands

- glide.lock
- glide.yaml
Sirupsen changed his username from Sirupsen to sirupsen, so the path of the `logrus` package has changed and glide needs to be updated to point to the new destination. The `github.com/prometheus/common` package also depended on the `logrus` package so I updated that package as well to its latest commit which updates their `logrus` dependency.
cc @prateek
> [glide] Update logrus dependency

- tools/deploy/planner.go
- tools/deploy/planner_test.go
cc @cw9 @prateek @jeromefroe 
This PR sorts the deployment targets in each deployment step by their instance IDs for deterministic ordering so it's easier to see in logs.
> Sort targets by instance id for deterministic ordering

- aggregator/handler/config.go
- aggregator/handler/writer/options.go
- aggregator/handler/writer/sharded.go
- aggregator/handler/writer/sharded_test.go
- glide.lock
- glide.yaml
cc @jeromefroe @cw9 @prateek 
This PR adds logic to support including encoding time when writing aggregate metrics, which allows us to compute end-to-end latency metrics (e.g., prior to ingest).
> Support including encoding time when writing aggregated metrics

- aggregator/placement_mgr.go
This PR removes deferred return and func execution in `Placement` on the hot path to save 2% CPU.
> Remove deferred return and func for CPU savings

- aggregator/map.go
- aggregator/map_test.go
- glide.lock
- glide.yaml
This PR pulls in latest m3x and replaces MD5 with 128-bit murmur3 as the id hashing function for improved efficiency with equally good if not better collision rate.
> Pull in latest m3x and replace MD5 with 128-bit murmur3 for id hash

- aggregator/aggregator.go
- aggregator/aggregator_test.go
- aggregator/placement_mgr.go
- aggregator/placement_mgr_test.go
- glide.lock
- glide.yaml
cc @jeromefroe @cw9 @prateek 
This PR pulls in latest m3cluster to handle placement updates and placement deletions gracefully. Specifically we attempt to update the shards in the aggregator if:
* If the staged placement has been updated (i.e.,  someone has updated the placement in KV), or
* There is a new placement in the staged placement that has recently become active and has a later cutover time.
If the placement is deleted from KV (presumably accidentally), the deletion is ignored and the agg tier will continue to use the cached placement. However, all further updates to the placements after the deletion are processed just like normal updates.
> Gracefully handle placement updates and deletions

- config/m3aggregator.yaml
- glide.lock
- glide.yaml
- services/m3aggregator/config/aggregator.go
Use kv configuration from m3cluster
Decouple the election kv namespace with the kv config, so they don't have to be the same namespace(although they still can)
@xichen2020 @jeromefroe
> Update m3cluster and m3metrics

- config/m3aggregator.yaml
- glide.lock
- glide.yaml
- services/m3aggregator/config/aggregator.go
This PR refactors the kv configuration for the agg tier to support different logging levels for different KV stores. Because m3cluster currently logs every kv update, and the agg tier persists flush times information to KV every 10s by default, this pollutes the log files and makes it difficult to find real issues. This PR moves kv config to individual manager configuration so the logging levels for different stores can be configured differently (e.g., use a log level of `warn` for the store that watches and persists flush times to reduce verbosity of logging)
> Refactor kv configuration to support different logging levels for different KV stores

- aggregator/follower_flush_mgr.go
- aggregator/follower_flush_mgr_test.go
- aggregator/leader_flush_mgr.go
- aggregator/leader_flush_mgr_test.go
This PR adds logic to retain flush times seen for kv persistence to fix a race condition during a topology change in which the leader instance closes a leaving shard and updates the persisted flush times before the follower instance gets a chance to process the persisted flush times in order to close the leaving shard.
The PR also refactored the follower flush manager and distinguishes between received flush times and process times, the latter of which is used to determine whether the follower instance can take over leadership, which is safer than using received times for that purpose.
> Retain flush times seen for KV persistence

- aggregator/entry.go
- aggregator/entry_pool_test.go
- aggregator/entry_test.go
- aggregator/map.go
- aggregator/map_test.go
- aggregator/options.go
- aggregator/options_test.go
- aggregator/types.go
- config/m3aggregator.yaml
- glide.lock
- glide.yaml
- integration/setup.go
- rate/limiter.go
- rate/limiter_test.go
- runtime/options.go
- runtime/options_manager.go
- runtime/options_manager_test.go
- server/msgpack/server.go
- services/m3aggregator/config/aggregator.go
- services/m3aggregator/config/aggregator_test.go
This PR adds rate limiting logic to limit the write rate per metric. The limit is backed by KV and disabled by default. This protects aggregation tier from being overwhelmed with high frequency metric emissions, and in extreme cases will allow us to perform load shedding to selectively drop values high-frequency metrics when the aggregation tier performance is suffering.
> Rate limiting per-metric writes

- server/msgpack/options.go
- server/msgpack/server.go
- services/m3aggregator/config/server.go
This PR adds rate limiting for error logs, so that for cases where we rate limit writes, the error logs are limited to a fix number of logs / second, instead of the full set.
> Rate limit error logging

- aggregator/entry.go
- aggregator/entry_test.go
- aggregator/map.go
- aggregator/map_test.go
- config/m3aggregator.yaml
- runtime/options.go
- runtime/options_test.go
- services/m3aggregator/config/aggregator.go
- services/m3aggregator/config/aggregator_test.go
- services/m3aggregator/config/kv.go
- services/m3aggregator/config/runtime.go
- services/m3aggregator/config/runtime_test.go
- services/m3aggregator/main/main.go
This PR adds rate limiting for new metric insertions after a configurable warmup period so that if a user started sending a large amount of high-cardinality metrics within a short time, the new entry creation requests will be rate limited to protect the aggregation tier from being overwhelmed.
> Rate limiting new metric insertions after warmup

- aggregator/follower_flush_mgr.go
- aggregator/leader_flush_mgr.go
This PR makes a shallow copy of the flushers slice so that if the original slice is modified during task execution (e.g., new flusher is registered or old flusher is unregistered), it won't cause a race condition.
> Make a copy of the flushers to fix race condition during shutdown

- aggregator/aggregator.go
- aggregator/flush_mgr.go
- aggregator/flush_mgr_test.go
This PR retains the flush bucket when reseting the shard set id associated with an instance so that after reset, the flush manager will continue flushing buckets that have been registered.
> Retain bucket during reset and add shard set id metrics

- aggregator/election_mgr.go
- aggregator/election_mgr_test.go
This PR adds logic to asynchronously resign from the ongoing campaign when the election manager is closed to avoid having lingering campaigns during process shutdown or shard set id reset.
Fixes #72 .
> Resign from ongoing campaign when election manager is closed

- aggregator/handler/common/router.go
- aggregator/handler/common/router_test.go
cc @cw9 @richardartoul 
This PR adds logic to protect the aggregator from closing the nil queue if the backend is only associated with a partial shardset.
> Do not close the nil queue for partial shardset

- .travis.yml
- glide.lock
- glide.yaml
- Pulled in latest m3x/m3cluster/m3metrics changes
- Ended up having to make changes to a few other packages e.g. protobuf, because of the version of etcd we're pinning was incompatible with the version of protobuf we were on. ref https://github.com/coreos/etcd/issues/7787 
Link line has changed a fair bit, probably want to test a deploy before landing this.
> Pull latest m3* packages

- aggregator/aggregator.go
- aggregator/elem.go
- aggregator/entry.go
- aggregator/map.go
- aggregator/options.go
- aggregator/shard.go
- bitset/bitset.go
- bitset/bitset_benchmark_test.go
- bitset/bitset_test.go
- glide.lock
- glide.yaml
- services/m3aggregator/config/aggregator.go
This PR adds logic to ingest untimed metrics with pipeline metadata at the aggregation tier.
> Ingest untimed metrics with pipeline metadata

- aggregator/counter_elem.gen.go
- aggregator/elem_base.go
- aggregator/entry.go
- aggregator/flush.go
- aggregator/gauge_elem.gen.go
- aggregator/generic_elem.go
- aggregator/list.go
- aggregator/options.go
- aggregator/timer_elem.gen.go
- glide.lock
- glide.yaml
- server/msgpack/server.go
- services/m3aggregator/config/aggregator.go
This PR adds logic to the aggregation elements to process aggregated metrics by flushing or forwarding them based on pipeline metadata.
NB: the changes in `*.gen.go` are auto-generated from `generic_elem.go`.
> Aggregation elements flush or forward metrics based on pipeline metadata

- .metalinter.json
- .travis.yml
- Makefile
This PR removes `lint` from the build targets since we seem to be getting the error below when installing golint. As such we remove `lint` and rely on `metalint` for linting. 
```
package golang.org/x/lint: unrecognized import path "golang.org/x/lint" (parse https://golang.org/x/lint?go-get=1: no go-import meta tags ())
```
> Remove lint from build target

- aggregator/aggregator.go
- aggregator/list.go
- aggregator/list_test.go
- aggregator/map.go
- aggregator/map_test.go
- aggregator/tick_result.go
This PR adds the logic to distinguish tick metrics for standard metrics from those for forwarded metrics to make it more clear on aggregator dashboards.
> Distinguish tick metrics for standard metrics and forwarded metrics

- aggregator/election_mgr.go
- aggregator/flush_times_mgr.go
- aggregator/flush_times_mgr_test.go
- aggregator/follower_flush_mgr.go
- aggregator/follower_flush_mgr_test.go
- aggregator/list.go
- aggregator/list_test.go
- client/client.go
- client/client_test.go
This PR adds logic to take into account forwarded metrics during deployment and leadership election.
> Add logic to take into account forwarded metrics during leadership election

- aggregator/aggregator_test.go
- aggregator/capture/aggregator_test.go
- aggregator/counter_elem.gen.go
- aggregator/elem_base.go
- aggregator/elem_base_test.go
- aggregator/elem_pool_test.go
- aggregator/elem_test.go
- aggregator/entry.go
- aggregator/entry_test.go
- aggregator/gauge_elem.gen.go
- aggregator/generic_elem.go
- aggregator/list_test.go
- aggregator/options.go
- aggregator/timer_elem.gen.go
- client/client_test.go
- client/config.go
- client/conn.go
- glide.lock
- glide.yaml
- integration/data.go
- integration/multi_server_forwarding_pipeline_test.go
- server/rawtcp/server_test.go
- services/m3aggregator/config/aggregator.go
- services/m3aggregator/config/server.go
cc @cw9 
This PR pulls in the latest m3metrics on tip of dev. It also initializes two bytes pool that weren't properly initialized previously.
> Pull in latest m3metrics dev

- client/config.go
- client/config_test.go
- services/m3aggregator/config/aggregator.go
This PR allows passing in clock options externally when creating agg tier client so the clock skews can be configured as needed.
> Allow passing in clock options when creating agg tier client

- glide.lock
- glide.yaml
This PR updates m3metrics to pick up latest type options API changes.
> Update m3metrics to pick up latest type options API changes

- glide.lock
- glide.yaml
cc @cw9 
This PR pulls in the latest m3metrics to close the migration iterator properly.
> Pull in latest m3metrics to close iterator properly

- aggregator/entry.go
- aggregator/entry_test.go
- integration/data.go
- integration/multi_server_forwarding_pipeline_test.go
This PR adds logic to allow multiple aggregation keys for forwarded metrics.
> Allow multiple aggregation keys for forwarded metrics

- glide.lock
- glide.yaml
cc @jskelcy @cw9 
This PR pulls latest m3metrics to unmarshal aggregation types as a list.
> Pull latest m3metrics to unmarshal aggregation types as a list

- aggregator/counter_elem.gen.go
- aggregator/elem_test.go
- aggregator/gauge_elem.gen.go
- aggregator/generic_elem.go
- aggregator/options.go
- aggregator/options_test.go
- aggregator/timer_elem.gen.go
- config/m3aggregator.yaml
- glide.lock
- glide.yaml
- integration/multi_server_forwarding_pipeline_test.go
- integration/options.go
- integration/setup.go
- services/m3aggregator/config/aggregator.go
This PR provides the logic to optionally discard NaN aggregated values and do not forward them to other servers for further aggregation or flush them to downstream services for indexing and storage.
Forwarding NaN values to other aggregation servers as part of the rollup pipeline will lead to NaN rollup metric values, which are currently treated as no datapoints in our query engine and therefore cause the entire rollup metric value to go "missing". Instead, we can optionally drop NaN values at the source so the multi-level rollup metrics are not affected as long as the remaining constituent metric values are non-NaN values.
> Do not flush NaN values downstream optionally

- aggregator/flush_mgr.go
- aggregator/flush_mgr_mock.go
- aggregator/flush_mgr_test.go
- aggregator/follower_flush_mgr.go
- aggregator/leader_flush_mgr.go
- aggregator/leader_flush_mgr_test.go
This PR adds logic to reset bucket next flush time to establish a limit on when a new flushing list will be flushed next.  This allows the follower to properly discard metrics and helps to speed up deployment in certain cases (e.g., when a leader just performed a flush and a new list is created immediately afterwards due to a new metric coming in with a new shard/resolution combination, and the follower wouldn't resign until the leader performs the next flush for the new list), both of which rely on the last flushed times of the flushers.
> Reset next flush time when new flusher is registered

- aggregator/counter_elem.gen.go
- aggregator/elem_base.go
- aggregator/elem_test.go
- aggregator/flush.go
- aggregator/flush_mock.go
- aggregator/follower_flush_mgr.go
- aggregator/follower_flush_mgr_test.go
- aggregator/gauge_elem.gen.go
- aggregator/generic_elem.go
- aggregator/leader_flush_mgr.go
- aggregator/leader_flush_mgr_test.go
- aggregator/list.go
- aggregator/list_test.go
- aggregator/timer_elem.gen.go
cc @cw9 
This PR adds logic so that followers only discard metrics based on the leader's schedule and do not consume forwarded metrics eagerly.
> Followers should not consume forwarded metrics eagerly

- aggregator/counter_elem.gen.go
- aggregator/forwarding_latency_histogram.go
- aggregator/forwarding_latency_histogram_test.go
- aggregator/gauge_elem.gen.go
- aggregator/generic_elem.go
- aggregator/timer_elem.gen.go
This PR adds logic so that the full forwarding latency histogram only records the latency when eager forwarding is allowed (i.e., for leader nodes) as the followers do not perform eager forwarding and only receive KV updates from leaders and as such the latency metrics are delayed and do not represent the actual e2e latency for forwarded metrics.
> Emit forwarding latency metrics when eager forwarding is allowed
